apiVersion: v1
kind: Service
metadata:
  name: gotodo
  labels:
    component: gotodo-core
spec:
  selector:
    component: gotodo-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gotodo-mysql
  labels:
    component: gotodo-database
spec:
  selector:
    component: gotodo-database
  ports:
    - protocol: TCP
      port: 33306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: gotodo-redis
  labels:
    component: gotodo-memcache
spec:
  selector:
    component: gotodo-memcache
  ports:
    - protocol: TCP
      port: 36379
      targetPort: 6379
